providers = ["node"]

[phases.install]
cmds = [
    "cd backend && npm install",
    "cd backend && npm run prisma:generate"
]

[start]
cmd = "cd backend && npx prisma db push --schema=src/prisma/schema.prisma --accept-data-loss && node src/scripts/setup-database.js && npm start"
